/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2;

/**
 *
 * @author ThinkPad X250
 */
import java2.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class anggota extends javax.swing.JFrame {

    /**
     * Creates new form anggota
     */
    public anggota() {
        initComponents();
        this.TampilData();
        bBaru.setEnabled(true);
        bsimpan.setEnabled(false);
        bedit.setEnabled(false);
        bhapus.setEnabled(false);
        nomoranggota.setVisible(true);
    }
private DefaultTableModel DftTblModel_anggota;
private String SQL;
public void TampilData() {
    DftTblModel_anggota = new DefaultTableModel();
    DftTblModel_anggota.addColumn("ID ANGGOTA");
    DftTblModel_anggota.addColumn("NAMA ANGGOTA");
    DftTblModel_anggota.addColumn("KELAS");
    DftTblModel_anggota.addColumn("JURUSAN");
    
    jtbanggota.setModel(DftTblModel_anggota);
    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement(); 
         SQL ="select * from tbanggota1";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_anggota.addRow(new Object []{
                res.getString ("nomor_anggota"),
                res.getString ("nama"),
                res.getString ("kelas"),
                res.getString ("jurusan"),
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
private void cariJudul(String key) {
DftTblModel_anggota = new DefaultTableModel();
    DftTblModel_anggota.addColumn("ID ANGGOTA");
    DftTblModel_anggota.addColumn("NAMA ANGGOTA");
    DftTblModel_anggota.addColumn("KELAS");
    DftTblModel_anggota.addColumn("JURUSAN");
    
    jtbanggota.setModel(DftTblModel_anggota);
    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement(); 
         SQL ="select * from tbanggota1 where nomor_anggota like '%"+key+"%'";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_anggota.addRow(new Object []{
                res.getString ("nomor_anggota"),
                res.getString ("nama"),
                res.getString ("kelas"),
                res.getString ("jurusan"),
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tkelas = new javax.swing.JTextField();
        tjurusan = new javax.swing.JTextField();
        nomoranggota = new javax.swing.JTextField();
        bBaru = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bclose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbanggota = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        carinomor = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel1.setText("ANGGOTA");

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel3.setText("KELAS");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel4.setText("JURUSAN");

        bBaru.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bBaru.setText("BARU");
        bBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaruActionPerformed(evt);
            }
        });

        bsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bclose.setText("CLOSE");
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        jtbanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbanggotaMouseClicked(evt);
            }
        });
        jtbanggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbanggotaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtbanggota);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CARI ");

        carinomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carinomorActionPerformed(evt);
            }
        });
        carinomor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carinomorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(252, 252, 252)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(tjurusan))
                                    .addGap(18, 18, 18)
                                    .addComponent(nomoranggota, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(carinomor, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bBaru)
                                .addGap(45, 45, 45)
                                .addComponent(bsimpan)
                                .addGap(45, 45, 45)
                                .addComponent(bedit)
                                .addGap(45, 45, 45)
                                .addComponent(bhapus)
                                .addGap(45, 45, 45)
                                .addComponent(bclose)))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomoranggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBaru)
                    .addComponent(bsimpan)
                    .addComponent(bedit)
                    .addComponent(bhapus)
                    .addComponent(bclose))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carinomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan logout?=","konfirmasi", JOptionPane.YES_NO_OPTION);
        if (pilih ==JOptionPane.YES_OPTION)
            dispose();
        else if (pilih ==JOptionPane.NO_OPTION){
            
        }
    }//GEN-LAST:event_bcloseActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("delete from tbanggota1 where nomor_anggota='"+nomoranggota.getText()+"'");
            stmt.executeUpdate();
            conn.close();
            TampilData();
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        try {
             Connection coon = koneksi.getConnection();
            PreparedStatement stmt = coon.prepareStatement("insert into tbanggota1(nama, kelas, jurusan) values (?,?,?)");
            stmt.setString(1, tnama.getText());
            stmt.setString(2, tkelas.getText());
            stmt.setString(3, tjurusan.getText());
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
            tnama.setText("");
            tkelas.setText("");
            tjurusan.setText("");
            nomoranggota.setText("");
            
        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaruActionPerformed
        // TODO add your handling code here:
        bBaru.setEnabled(true);
        bsimpan.setEnabled(true);
        bedit.setEnabled(true);
        bhapus.setEnabled(true);
    }//GEN-LAST:event_bBaruActionPerformed

    private void jtbanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbanggotaMouseClicked
        // TODO add your handling code here:
        int baris = jtbanggota.getSelectedRow();
        tnama.setText(DftTblModel_anggota.getValueAt(baris, 1).toString());
        tkelas.setText(DftTblModel_anggota.getValueAt(baris, 2).toString());
        tjurusan.setText(DftTblModel_anggota.getValueAt(baris, 3).toString());
        nomoranggota.setText(DftTblModel_anggota.getValueAt(baris, 0).toString());
        
        bBaru.setEnabled(true);
        bsimpan.setEnabled(true);
        bedit.setEnabled(true);
        bhapus.setEnabled(true);
    }//GEN-LAST:event_jtbanggotaMouseClicked

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("update tbanggota1 set nama=?, kelas=?, jurusan=? where nomor_anggota=?");
            stmt.setString(1, tnama.getText());
            stmt.setString(2, tkelas.getText());
            stmt.setString(3, tjurusan.getText());
            stmt.setString(4, nomoranggota.getText());
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
            
            tnama.setText("");
            tkelas.setText("");
            tjurusan.setText("");
            nomoranggota.setText("");
            
             bBaru.setEnabled(true);
             bsimpan.setEnabled(true);
             bedit.setEnabled(true);
             bhapus.setEnabled(true);
             
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_beditActionPerformed

    private void jtbanggotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbanggotaKeyReleased
        // TODO add your handling code here:
        String key=carinomor.getText();
        System.out.println(key);
        
        if(key!=""){
            cariJudul(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_jtbanggotaKeyReleased

    private void carinomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carinomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carinomorActionPerformed

    private void carinomorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carinomorKeyReleased
        // TODO add your handling code here:
        String key=carinomor.getText();
        System.out.println(key);

        if(key!=""){
            cariJudul(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_carinomorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBaru;
    private javax.swing.JButton bclose;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JTextField carinomor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtbanggota;
    private javax.swing.JTextField nomoranggota;
    private javax.swing.JTextField tjurusan;
    private javax.swing.JTextField tkelas;
    private javax.swing.JTextField tnama;
    // End of variables declaration//GEN-END:variables
}
