/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2;

/**
 *
 * @author ThinkPad X250
 */
import java2.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public laporan() {
        initComponents();
    }
private DefaultTableModel DftTblModel_tampil;
private String SQL;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        menampilkan = new javax.swing.JButton();
        pilihan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        penerbit = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        petugas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        anggota = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        buku = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        peminjaman = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("LAPORAN ");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        menampilkan.setText("menampilkan");
        menampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menampilkanActionPerformed(evt);
            }
        });

        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "peminjaman_buku", "penerbit", "petugas", "anggota", "buku", "peminjaman" }));

        penerbit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(penerbit);

        petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(petugas);

        anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(anggota);

        jButton1.setText("menampilkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("menampilkan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("menampilkan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(buku);

        jButton4.setText("menampilkan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(peminjaman);

        jButton5.setText("menampilkan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(menampilkan)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(menampilkan)
                                    .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menampilkanActionPerformed
        // TODO add your handling code here:
        if(pilihan.getSelectedItem().toString().equalsIgnoreCase("peminjaman_buku")){
            DftTblModel_tampil = new DefaultTableModel();
            DftTblModel_tampil.addColumn("JUDUL BUKU");
            DftTblModel_tampil.addColumn("DIPINJAM OLEH");
            DftTblModel_tampil.addColumn("TANGGAL PEMINJAMAN");
            DftTblModel_tampil.addColumn("DIURUS OLEH");
    
            tabel.setModel(DftTblModel_tampil);
            Connection conn = koneksi.getConnection();
            try {
                java.sql.Statement stmt = conn.createStatement(); 
                SQL ="SELECT tbbuku.judulbuku, tbpeminjam.nama, tbpeminjam.tglpinjam, tbpetugas.namapetugas FROM tbbuku INNER JOIN tbpeminjam on tbbuku.idbuku=tbpeminjam.nopinjam INNER JOIN tbpetugas on tbbuku.idbuku=tbpetugas.idpetugas";
                java.sql.ResultSet res = stmt.executeQuery(SQL);
                 while (res.next()) {
  
                    DftTblModel_tampil.addRow(new Object []{
                res.getString ("judulbuku"),
                res.getString ("nama"),
                res.getString ("tglpinjam"),
                res.getString ("namapetugas"),
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
            
        
    }//GEN-LAST:event_menampilkanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(pilihan.getSelectedItem().toString().equalsIgnoreCase("penerbit")){
            DftTblModel_tampil = new DefaultTableModel();
            DftTblModel_tampil.addColumn("TELP PENERBIT");
            DftTblModel_tampil.addColumn("ALAMAT PENERBIT");
            DftTblModel_tampil.addColumn("DITERBITKAN OLEH");
    
            penerbit.setModel(DftTblModel_tampil);
            Connection conn = koneksi.getConnection();
            try {
                java.sql.Statement stmt = conn.createStatement(); 
                SQL ="select * from tbpenerbit";
                java.sql.ResultSet res = stmt.executeQuery(SQL);
                 while (res.next()) {
  
                    DftTblModel_tampil.addRow(new Object []{
                res.getString ("telp"),
                res.getString ("alamat"),
                res.getString ("namapenerbit"),
                
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(pilihan.getSelectedItem().toString().equalsIgnoreCase("petugas")){
            DftTblModel_tampil = new DefaultTableModel();
            DftTblModel_tampil.addColumn("USER NAME");
            DftTblModel_tampil.addColumn("PASSWORD");
            DftTblModel_tampil.addColumn("DITUGASKAN");
    
            petugas.setModel(DftTblModel_tampil);
            Connection conn = koneksi.getConnection();
            try {
                java.sql.Statement stmt = conn.createStatement(); 
                SQL ="select * from tbpetugas";
                java.sql.ResultSet res = stmt.executeQuery(SQL);
                 while (res.next()) {
  
                    DftTblModel_tampil.addRow(new Object []{
                res.getString ("username"),
                res.getString ("password"),
                res.getString ("namapetugas"),
                
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(pilihan.getSelectedItem().toString().equalsIgnoreCase("anggota")){
            DftTblModel_tampil = new DefaultTableModel();
            DftTblModel_tampil.addColumn("KELAS ");
            DftTblModel_tampil.addColumn("JURUSAN");
            DftTblModel_tampil.addColumn("NAMA ANGGOTA");
    
            anggota.setModel(DftTblModel_tampil);
            Connection conn = koneksi.getConnection();
            try {
                java.sql.Statement stmt = conn.createStatement(); 
                SQL ="select * from tbanggota1";
                java.sql.ResultSet res = stmt.executeQuery(SQL);
                 while (res.next()) {
  
                    DftTblModel_tampil.addRow(new Object []{
                res.getString ("kelas"),
                res.getString ("jurusan"),
                res.getString ("nama"),
                
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(pilihan.getSelectedItem().toString().equalsIgnoreCase("buku")){
       DftTblModel_tampil = new DefaultTableModel();
        DftTblModel_tampil.addColumn("judulbuku");
        DftTblModel_tampil.addColumn("penerbit");
        DftTblModel_tampil.addColumn("jumlah");

    buku.setModel(DftTblModel_tampil);
    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement(); 
         SQL ="select * from tbbuku";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_tampil.addRow(new Object []{
                res.getString ("judulbuku"),
                res.getString ("penerbit"),
                res.getString ("jumlah"),
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    } }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(pilihan.getSelectedItem().toString().equalsIgnoreCase("peminjaman")){
        DftTblModel_tampil = new DefaultTableModel();
        DftTblModel_tampil.addColumn("JUDUL BUKU");
        DftTblModel_tampil.addColumn("NAMA PEMINJAM");
        DftTblModel_tampil.addColumn("TGL PINJAM");
        DftTblModel_tampil.addColumn("TGL KEMBALI");
        DftTblModel_tampil.addColumn("TERLAMBAT");

    peminjaman.setModel(DftTblModel_tampil);
    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement(); 
         SQL ="select * from tbpeminjam";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_tampil.addRow(new Object []{
                res.getString ("judulbuku"),
                res.getString ("nama"),
                res.getString ("tglpinjam"),
                res.getString ("tglkembali"),
                res.getString ("terlambat"),
                
                
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable anggota;
    private javax.swing.JTable buku;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton menampilkan;
    private javax.swing.JTable peminjaman;
    private javax.swing.JTable penerbit;
    private javax.swing.JTable petugas;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}

