/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2;

/**
 *
 * @author ThinkPad X250
 */
import java2.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class peminjam extends javax.swing.JFrame {

    /**
     * Creates new form peminjam
     */
    public peminjam() {
        initComponents();
        this.TampilData();
        bBaru.setEnabled(true);
        bsimpan.setEnabled(false);
        bedit.setEnabled(false);
        bhapus.setEnabled(false);
        tnopeminjam.setVisible(true);
    }
private DefaultTableModel DftTblModel_peminjam;
private String SQL;
public void TampilData() {
    DftTblModel_peminjam = new DefaultTableModel();
    DftTblModel_peminjam.addColumn("NO PINJAM");
    DftTblModel_peminjam.addColumn("JUDUL BUKU");
    DftTblModel_peminjam.addColumn("NAMA PEMINJAM");
    DftTblModel_peminjam.addColumn("TGL PINJAM");
    DftTblModel_peminjam.addColumn("TGL KEMBALI");
    DftTblModel_peminjam.addColumn("TERLAMBAT");
    
    jtbpeminjam.setModel(DftTblModel_peminjam);
    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement(); 
         SQL ="select * from tbpeminjam";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_peminjam.addRow(new Object []{
                res.getString ("nopinjam"),
                res.getString ("judulbuku"),
                res.getString ("nama"),
                res.getString ("tglpinjam"),
                res.getString ("tglkembali"),
                res.getString ("terlambat"),
                
                
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
private void cariJudul(String key) {
    DftTblModel_peminjam = new DefaultTableModel();
    DftTblModel_peminjam.addColumn("NO PINJAM");
    DftTblModel_peminjam.addColumn("JUDUL BUKU");
    DftTblModel_peminjam.addColumn("NAMA PEMINJAM");
    DftTblModel_peminjam.addColumn("TGL PINJAM");
    DftTblModel_peminjam.addColumn("TGL KEMBALI");
    DftTblModel_peminjam.addColumn("TERLAMBAT");
    
    jtbpeminjam.setModel(DftTblModel_peminjam);
    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement(); 
         SQL ="select * from tbpeminjam where judulbuku like '%"+key+"%'";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_peminjam.addRow(new Object []{
                res.getString ("nopinjam"),
                res.getString ("judulbuku"),
                res.getString ("nama"),
                res.getString ("tglpinjam"),
                res.getString ("tglkembali"),
                res.getString ("terlambat"),
                
                
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbpeminjam = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        tglpinjam = new javax.swing.JTextField();
        tnopeminjam = new javax.swing.JTextField();
        bBaru = new javax.swing.JButton();
        terlambat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tglkembali = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bclose.setText("CLOSE");
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        jtbpeminjam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbpeminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbpeminjam.setName(""); // NOI18N
        jtbpeminjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbpeminjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbpeminjam);

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel1.setText("PEMINJAMAN");

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel2.setText("JUDUL BUKU");

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel3.setText("NAMA PEMINJAM");

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel4.setText("TANGGAL PINJAM");

        judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulActionPerformed(evt);
            }
        });

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        tglpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglpinjamActionPerformed(evt);
            }
        });

        tnopeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnopeminjamActionPerformed(evt);
            }
        });

        bBaru.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bBaru.setText("BARU");
        bBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaruActionPerformed(evt);
            }
        });

        terlambat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terlambatActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel5.setText("TANGGAL KEMBALI");

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel6.setText("TERLAMBAT");

        tglkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglkembaliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("CARI ");

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bBaru)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(bsimpan)
                                .addGap(62, 62, 62)
                                .addComponent(bedit)
                                .addGap(62, 62, 62)
                                .addComponent(bhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(bclose))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(terlambat, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tnopeminjam))))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnopeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(terlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBaru)
                    .addComponent(bsimpan)
                    .addComponent(bedit)
                    .addComponent(bhapus)
                    .addComponent(bclose))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        try {
            Connection coon = koneksi.getConnection();
            PreparedStatement stmt = coon.prepareStatement("insert into tbpeminjam(judulbuku, nama, tglpinjam, tglkembali, terlambat) values (?,?,?,?,?)");
            stmt.setString(1, judul.getText());
            stmt.setString(2, nama.getText());
            stmt.setString(3, tglpinjam.getText());
            stmt.setString(4, tglkembali.getText());
            stmt.setString(5, terlambat.getText());

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
            judul.setText("");
            nama.setText("");
            tglpinjam.setText("");
            tglkembali.setText("");
            terlambat.setText("");
            tnopeminjam.setText("");

        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("update tbpeminjam set judulbuku=?, nama=?, tglpinjam=?, tglkembali=?, terlambat=? where nopinjam=?");
            stmt.setString(1, judul.getText());
            stmt.setString(2, nama.getText());
            stmt.setString(3, tglpinjam.getText());
            stmt.setString(4, tglkembali.getText());
            stmt.setString(5, terlambat.getText());
            stmt.setString(6, tnopeminjam.getText());

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();

            judul.setText("");
            nama.setText("");
            tglpinjam.setText("");
            tglkembali.setText("");
            terlambat.setText("");
            tnopeminjam.setText("");

            bBaru.setEnabled(true);
            bsimpan.setEnabled(true);
            bedit.setEnabled(true);
            bhapus.setEnabled(true);

        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("delete from tbpeminjam where nopinjam='"+tnopeminjam.getText()+"'");
            stmt.executeUpdate();
            conn.close();
            TampilData();
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan logout?=","konfirmasi", JOptionPane.YES_NO_OPTION);
        if (pilih ==JOptionPane.YES_OPTION)
        dispose();
        else if (pilih ==JOptionPane.NO_OPTION){

        }
    }//GEN-LAST:event_bcloseActionPerformed

    private void jtbpeminjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbpeminjamMouseClicked
        // TODO add your handling code here:
        int baris = jtbpeminjam.getSelectedRow();
        judul.setText(DftTblModel_peminjam.getValueAt(baris, 1).toString());
        nama.setText(DftTblModel_peminjam.getValueAt(baris, 2).toString());
        tglpinjam.setText(DftTblModel_peminjam.getValueAt(baris, 3).toString());
        tglkembali.setText(DftTblModel_peminjam.getValueAt(baris, 4).toString());
        terlambat.setText(DftTblModel_peminjam.getValueAt(baris, 5).toString());
        tnopeminjam.setText(DftTblModel_peminjam.getValueAt(baris, 0).toString());

        bBaru.setEnabled(true);
        bsimpan.setEnabled(true);
        bedit.setEnabled(true);
        bhapus.setEnabled(true);
    }//GEN-LAST:event_jtbpeminjamMouseClicked

    private void judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void tglpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamActionPerformed

    private void tnopeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnopeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnopeminjamActionPerformed

    private void bBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaruActionPerformed
        // TODO add your handling code here:
        bBaru.setEnabled(true);
        bsimpan.setEnabled(true);
        bedit.setEnabled(true);
        bhapus.setEnabled(true);
    }//GEN-LAST:event_bBaruActionPerformed

    private void terlambatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terlambatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terlambatActionPerformed

    private void tglkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglkembaliActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        String key=cari.getText();
        System.out.println(key);

        if(key!=""){
            cariJudul(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBaru;
    private javax.swing.JButton bclose;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbpeminjam;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField terlambat;
    private javax.swing.JTextField tglkembali;
    private javax.swing.JTextField tglpinjam;
    private javax.swing.JTextField tnopeminjam;
    // End of variables declaration//GEN-END:variables
}
