/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sekolah;

/**
 *
 * @author ThinkPad X250
 */
import sekolah.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
public class datasiswa extends javax.swing.JFrame {

    /**
     * Creates new form datasiswa
     */
    public datasiswa() {
        initComponents();
        this.TampilData();
        bBaru.setEnabled(true);
        bsimpan.setEnabled(false);
        bedit.setEnabled(false);
        bhapus.setEnabled(false);
        idsiswa.setVisible(true);
    }
private DefaultTableModel DftTblModel_siswa;
private String SQL;
public void TampilData() {
    DftTblModel_siswa = new DefaultTableModel();
    DftTblModel_siswa.addColumn("idsiswa");
    DftTblModel_siswa.addColumn("namasiswa");
    DftTblModel_siswa.addColumn("jenis kelamin");
    DftTblModel_siswa.addColumn("alamat");
    DftTblModel_siswa.addColumn("kelas");
    DftTblModel_siswa.addColumn("anakke");
    DftTblModel_siswa.addColumn("hobby");
    DftTblModel_siswa.addColumn("cita-cita");
    
    siswa.setModel(DftTblModel_siswa);
    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement(); 
         SQL ="select * from dbdatasiswa";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_siswa.addRow(new Object []{
                res.getString ("idsiswa"),
                res.getString ("namasiswa"),
                res.getString ("jeniskelamin"),
                res.getString ("alamat"),
                res.getString ("kelas"),
                res.getString ("anakke"),
                res.getString ("hobby"),
                res.getString ("cita"),
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }
}
private void cariJudul(String key) {
    DftTblModel_siswa = new DefaultTableModel();
    DftTblModel_siswa.addColumn("idsiswa");
    DftTblModel_siswa.addColumn("namasiswa");
    DftTblModel_siswa.addColumn("jenis kelamin");
    DftTblModel_siswa.addColumn("alamat");
    DftTblModel_siswa.addColumn("kelas");
    DftTblModel_siswa.addColumn("anakke");
    DftTblModel_siswa.addColumn("hobby");
    DftTblModel_siswa.addColumn("cita-cita");
    
    siswa.setModel(DftTblModel_siswa);
    Connection conn = koneksi.getConnection();
    try {
        java.sql.Statement stmt = conn.createStatement(); 
         SQL ="select * from dbdatasiswa where idsiswa like '%"+key+"%'";
        java.sql.ResultSet res = stmt.executeQuery(SQL);
        while (res.next()) {
            DftTblModel_siswa.addRow(new Object []{
                res.getString ("idsiswa"),
                res.getString ("namasiswa"),
                res.getString ("jeniskelamin"),
                res.getString ("alamat"),
                res.getString ("kelas"),
                res.getString ("anakke"),
                res.getString ("hobby"),
                res.getString ("cita"),
            });
        }
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bhapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bclose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        siswa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ns = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        idsiswa = new javax.swing.JTextField();
        bBaru = new javax.swing.JButton();
        hobby = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        anak = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cita = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel1.setText("DATA SISWA");

        bhapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel2.setText("NAMA SISWA");

        bclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bclose.setText("CLOSE");
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel3.setText("JENIS KELAMIN");

        siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaMouseClicked(evt);
            }
        });
        siswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                siswaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(siswa);

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel4.setText("ALAMAT");

        ns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CARI ");

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        idsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsiswaActionPerformed(evt);
            }
        });

        bBaru.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bBaru.setText("BARU");
        bBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaruActionPerformed(evt);
            }
        });

        hobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobbyActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel6.setText("KELAS");

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel7.setText("ANAK-KE");

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel8.setText("HOBBY");

        anak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anakActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel9.setText("CITA-CITA");

        cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(210, 210, 210)
                                .addComponent(cita, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(ns)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(idsiswa))
                                    .addComponent(jk)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(217, 217, 217)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(anak, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                                    .addComponent(hobby, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kelas))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bBaru)
                        .addGap(33, 33, 33)
                        .addComponent(bsimpan)
                        .addGap(38, 38, 38)
                        .addComponent(bedit)
                        .addGap(43, 43, 43)
                        .addComponent(bhapus)
                        .addGap(38, 38, 38)
                        .addComponent(bclose)
                        .addGap(57, 57, 57))))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(anak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(hobby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBaru)
                    .addComponent(bsimpan)
                    .addComponent(bedit)
                    .addComponent(bhapus)
                    .addComponent(bclose))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        try {
            Connection coon = koneksi.getConnection();
            PreparedStatement stmt = coon.prepareStatement("insert into dbdatasiswa(namasiswa, jeniskelamin, alamat, kelas, anakke, hobby, cita) values (?,?,?,?,?,?,?)");
            stmt.setString(1, ns.getText());
            stmt.setString(2, jk.getText());
            stmt.setString(3, alamat.getText());
            stmt.setString(4, kelas.getText());
            stmt.setString(5, anak.getText());
            stmt.setString(6, hobby.getText());
            stmt.setString(7, cita.getText());
            

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
            ns.setText("");
            jk.setText("");
            alamat.setText("");
            kelas.setText("");
            anak.setText("");
            hobby.setText("");
            cita.setText("");
            idsiswa.setText("");

        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("update dbdatasiswa set namasiswa=?, jeniskelamin=?, alamat=?, kelas=?, anakke=?, hobby=?, cita=? where idsiswa=?");
           stmt.setString(1, ns.getText());
            stmt.setString(2, jk.getText());
            stmt.setString(3, alamat.getText());
            stmt.setString(4, kelas.getText());
            stmt.setString(5, anak.getText());
            stmt.setString(6, hobby.getText());
            stmt.setString(7, cita.getText());
            stmt.setString(8, idsiswa.getText());
            
            

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();

            ns.setText("");
            jk.setText("");
            alamat.setText("");
            kelas.setText("");
            anak.setText("");
            hobby.setText("");
            cita.setText("");
            idsiswa.setText("");

            bBaru.setEnabled(true);
            bsimpan.setEnabled(true);
            bedit.setEnabled(true);
            bhapus.setEnabled(true);

        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("delete from dbdatasiswa where idsiswa='"+idsiswa.getText()+"'");
            stmt.executeUpdate();
            conn.close();
            TampilData();
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan logout?=","konfirmasi", JOptionPane.YES_NO_OPTION);
        if (pilih ==JOptionPane.YES_OPTION)
        dispose();
        else if (pilih ==JOptionPane.NO_OPTION){

        }
    }//GEN-LAST:event_bcloseActionPerformed

    private void siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaMouseClicked
        // TODO add your handling code here:
        int baris = siswa.getSelectedRow();
        ns.setText(DftTblModel_siswa.getValueAt(baris, 1).toString());
        jk.setText(DftTblModel_siswa.getValueAt(baris, 2).toString());
        alamat.setText(DftTblModel_siswa.getValueAt(baris, 3).toString());
        kelas.setText(DftTblModel_siswa.getValueAt(baris, 4).toString());
        anak.setText(DftTblModel_siswa.getValueAt(baris, 5).toString());
        hobby.setText(DftTblModel_siswa.getValueAt(baris, 6).toString());
        cita.setText(DftTblModel_siswa.getValueAt(baris, 7).toString());
        idsiswa.setText(DftTblModel_siswa.getValueAt(baris, 0).toString());

        bBaru.setEnabled(true);
        bsimpan.setEnabled(true);
        bedit.setEnabled(true);
        bhapus.setEnabled(true);
    }//GEN-LAST:event_siswaMouseClicked

    private void siswaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_siswaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_siswaKeyReleased

    private void nsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nsActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        String key=cari.getText();
        System.out.println(key);

        if(key!=""){
            cariJudul(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_cariKeyReleased

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void idsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsiswaActionPerformed

    private void bBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaruActionPerformed
        // TODO add your handling code here:
        bBaru.setEnabled(true);
        bsimpan.setEnabled(true);
        bedit.setEnabled(true);
        bhapus.setEnabled(true);
    }//GEN-LAST:event_bBaruActionPerformed

    private void hobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hobbyActionPerformed

    private void anakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anakActionPerformed

    private void citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField anak;
    private javax.swing.JButton bBaru;
    private javax.swing.JButton bclose;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField cita;
    private javax.swing.JTextField hobby;
    private javax.swing.JTextField idsiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField ns;
    private javax.swing.JTable siswa;
    // End of variables declaration//GEN-END:variables
}
